[package]
name = 'pallet-profiles'
version = '0.6.1'
authors = ['DappForce <dappforce@pm.me>', 'JosephKnecht <info@universaldot,foundation>']
edition = '2018'
license = 'GPL-3.0-only'
description = 'Pallet to manage social accounts and profiles'
keywords = ['blockchain', 'cryptocurrency', 'social-network', 'news-feed', 'marketplace']
categories = ['cryptography::cryptocurrencies']

[features]
default = ['std']
std = [
    'serde',
    'codec/std',
    'frame-support/std',
    'frame-system/std',
    'sp-runtime/std',
    'sp-std/std',
    'pallet-permissions/std',
    'pallet-utils/std',
]

[dependencies.serde]
optional = true
features = ['derive']
version = "1.0.119"

[dependencies.codec]
default-features = false
features = ['derive']
package = 'parity-scale-codec'
version = '1.3.4'

[dependencies]
impl-trait-for-tuples = '0.1.3'

# Local dependencies
pallet-permissions = { default-features = false, path = '../permissions' }
pallet-utils = { default-features = false, path = '../utils' }

# Substrate dependencies
frame-support = { default-features = false, version = '2.0.1' }
frame-system = { default-features = false, version = '2.0.1' }
sp-runtime = { default-features = false, version = '2.0.1' }
sp-std = { default-features = false, version = '2.0.1' }
